Add push to main

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -17,13 +17,14 @@ on:
         required: true
         type: string
         default: 'origin/main'
+  push:
+    branches:
+      - main
 
 jobs:
   deploy:
-    name: Deploy to ${{ github.event.inputs.environment }}
+    name: Deploy Aggregator
     runs-on: ubuntu-latest
-    environment:
-      name: "${{ github.event.inputs.environment }}"
 
     steps:
 
@@ -36,12 +37,29 @@ jobs:
       - name: Process input
         id: process_input
         run: |
-          raw_input="${{ github.event.inputs.aggregator_tag }}"
-          trimmed_input=$(echo "$raw_input" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
-          COMMIT_ID=$(git rev-parse "${trimmed_input}")
+          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]
+          then
+            echo "Triggered by: workflow_dispatch"
+            raw_input="${{ github.event.inputs.aggregator_tag }}"
+            trimmed_input=$(echo "$raw_input" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
+            COMMIT_ID=$(git rev-parse "${trimmed_input}")
+            ENVIRONMENT="${{ github.event.inputs.environment }}"
+          elif [[ "${{ github.event_name }}" == "push" ]]; then
+            echo "Triggered by: push to main"
+            COMMIT_ID=$(git rev-parse "origin/main")
+            ENVIRONMENT="devnet"
+          else
+            echo "::error::Unsupported event type: ${{ github.event_name }}"
+            exit 1
+          fi
+
+          # input parameters
           echo "commit_id=${COMMIT_ID}"
-          docker manifest inspect "ghcr.io/unicitynetwork/aggregators_net:${COMMIT_ID}"
           echo "commit_id=${COMMIT_ID}" >> $GITHUB_OUTPUT
+          echo "environment=${ENVIRONMENT}"
+          echo "environment=${ENVIRONMENT}" >> $GITHUB_OUTPUT
+          # check if docker image exists
+          docker manifest inspect "ghcr.io/unicitynetwork/aggregators_net:${COMMIT_ID}"
 
       - name: Set up Python
         uses: actions/setup-python@v5
@@ -96,6 +114,6 @@ jobs:
           chmod 600 .vault_pass
 
           ansible-playbook aggregator.yml \
-          -e "env=${{ github.event.inputs.environment }}" \
+          -e "env=${{ steps.process_input.outputs.environment }}" \
           -e "aggregator_tag=${{ steps.process_input.outputs.commit_id }}"
 
